data_arguments:
  data_dir: /home/liang/dataset/wsi/combine/tests/hsil
  data_dir_key: source
  label_dict:
    hsil: 1
    normal: 0
  preset: clam/presets/bwh_biopsy.csv
  process_list: clam/heatmaps/configs/heatmap_demo_dataset_hsil.csv
  slide_ext: .svs
exp_arguments:
  batch_size: 128
  n_classes: 2
  production_save_dir: clam/heatmaps/heatmap_production_results
  raw_save_dir: clam/heatmaps/heatmap_raw_results
  save_exp_code: HEATMAP_OUTPUT
heatmap_arguments:
  alpha: 0.4
  binarize: false
  binary_thresh: -1
  blank_canvas: false
  blur: false
  calc_heatmap: true
  cmap: jet
  custom_downsample: 1
  save_ext: jpg
  save_orig: true
  use_center_shift: true
  use_ref_scores: true
  use_roi: false
  vis_level: 1
model_arguments:
  ckpt_path: results/combine/bag_sb_model_s1/s_9_checkpoint.pt
  drop_out: true
  initiate_fn: initiate_model
  model_size: small
  model_type: clam_sb
  n_classes: 2
  slf_ckpt_path: results/checkpoints/resnet50_hsil/slfcd-19-0.01.ckpt
patching_arguments:
  custom_downsample: 1
  overlap: 0.5
  patch_level: 0
  patch_size: 256
sample_arguments:
  samples:
  - k: 15
    mode: topk
    name: topk_high_attention
    sample: true
    seed: 1
